databases:
  - name: go-meeting
    region: singapore
    databaseName: meeting_room_production
    user: meeting_room
    plan: free

services:
  - type: redis
    name: go-meeting-sidekiq-redis
    maxmemoryPolicy: noeviction
    region: singapore
    ipAllowList: [] # only allow internal connections
    plan: free

  - type: web
    name: go-meeting-sidekiq
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: "bundle install"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec sidekiq -C config/sidekiq.yml"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: go-meeting-sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

  - type: web
    name: GoMeeting
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: go-meeting-sidekiq-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: go-meeting
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
